apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: controls
  name: data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
# Usado para descarga de Script.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-init
  namespace: controls
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/scripts"