apiVersion: v1
kind: Service
metadata:
  name: controls
  namespace: controls
  labels:
    app: controls
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: controls
  type: LoadBalancer