apiVersion: v1
kind: Service
metadata:
  name: controls
  namespace: controls
  labels:
    app: controls
spec:
  selector:
    app: controls
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80